homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: -26.2309
  longitude: 28.0583
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1693
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Africa/Johannesburg
  customize:
    sensor.yr_temperature:
      friendly_name: Predicted Temp
    sensor.yr_humidity:
      friendly_name: Predicted Humidity
    sensor.yr_precipitation:
      friendly_name: Predicted Rain
    sensor.yr_pressure:
      friendly_name: Predicted Pressure
    sensor.yr_symbol:
      friendly_name: Weather Symbol

automation: !include automations.yaml 
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret the_password
  ssl_certificate: /etc/letsencrypt/live/kydhome.dyndns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/kydhome.dyndns.org/privkey.pem

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor weather:
  platform: yr
  monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - pressure
      - humidity

alarm_control_panel:
  platform: mqtt
  name: "Armed Status"
  state_topic: "homeassistant/sensor/alarm/armed"  
  command_topic: "homeassistant/sensor/alarm/set"

switch: !include switches.yaml
sensor: !include sensor.yaml

input_select:
  entertainment_system_volume:
    name: Entertainment System Volume
    options:
      - 'Up+++'
      - 'Up++'
      - 'Up+'
      - 'Nothing'      
      - 'Down-'
      - 'Down--'
      - 'Down---'
    initial: 'Nothing'

ifttt:
  key: dUhm_MDfeHCOw2yJROuiXh

mqtt:
  broker: 192.168.1.54

recorder:
  purge_days: 10  

notify:
  name: alarmstatusnotifier
  platform: pushbullet
  api_key: o.RXa6SLEp5XVVrNVRGWFCIngie3h7PeMj

group: !include groups.yaml